#!/bin/bash

# Write a script to run your optimizer in this file 
# This script should take 2 command line arguments: a path to 
# the input ir file and a path where the output ir file should
# be created.
set -e

if [ "$#" -ne 2 ]; then
	echo "Usage: bash run.sh <input_ir> <output_ir>" >&2
	exit 1
fi

# Run optimizer using classes generated by build.sh.
java -cp build TigerOptimizer "$1" "$2"